server:
  port: 8081
  error:
    path: /error2

spring:
  application:
    name: Bootstrap Spring Boot
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html